# Generated by Django 5.2.5 on 2025-10-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_board_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
    ]
