# Generated by Django 5.1.4 on 2025-09-29 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_filecard_card'),
        ('checklist', '0002_alter_checklist_is_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='board',
        ),
        migrations.AddField(
            model_name='checklist',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='card.card', verbose_name='Card'),
        ),
    ]
