# Generated by Django 5.2.5 on 2025-08-28 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=155, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('image', models.URLField(blank=True, default='https://storage.googleapis.com/star-lab/blog/OGs/image-not-found.png', null=True, verbose_name='Imagem')),
                ('status', models.CharField(choices=[('todo', 'A Fazer'), ('in_progress', 'Em Progresso'), ('review', 'Em Revisão'), ('done', 'Concluído'), ('disapprove', 'Reprovado')], default='todo', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Data de entrega')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='card.card', verbose_name='Card')),
            ],
            options={
                'verbose_name': 'Feedback do card',
                'verbose_name_plural': 'Feedbacks dos cards',
            },
        ),
    ]
