# Generated by Django 5.2.5 on 2025-10-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_filecard_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecard',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Está aprovado'),
        ),
    ]
