# Generated by Django 5.2.5 on 2025-10-02 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_alter_filecard_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filecard',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='card.card', verbose_name='Card'),
        ),
    ]
